application: go-slidown
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /js/index.js
  static_files: index.js
  upload: index.js

- url: /css/index.css
  static_files: index.css
  upload: index.css

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /.*
  script: _go_app

env_variables:
  # your SlideShare token
  APIKEY:
  SHAREDSECRET: