application: go-slidown
version: 1
runtime: go
api_version: go1

basic_scaling:
  max_instances: 5
  idle_timeout: 5m

handlers:
- url: /api/.*
  script: _go_app

- url: /_ah/start
  script: _go_app

- url: /_ah/stop
  script: _go_app

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static

env_variables:
  # your SlideShare token
  APIKEY: 
  SHAREDSECRET: 
  CREATEPDF: 
  BUCKETNAME: 